// sdk/nuxt/src/runtime/components/AddressForm.vue
<template>
  <div class="vey-address-form">
    <div class="form-group">
      <label for="country">Country</label>
      <select id="country" v-model="countryCode" @change="errors = []">
        <option value="">Select a country</option>
        <option v-for="country in countries" :key="country.code" :value="country.code">
          {{ country.name }}
        </option>
      </select>
    </div>

    <div v-if="countryCode" class="form-group">
      <label for="street">Street Address</label>
      <input id="street" v-model="address.street" type="text" />
    </div>

    <div v-if="countryCode" class="form-group">
      <label for="city">City</label>
      <input id="city" v-model="address.city" type="text" />
    </div>

    <div v-if="countryCode" class="form-group">
      <label for="postalCode">Postal Code</label>
      <input id="postalCode" v-model="address.postalCode" type="text" />
    </div>

    <button @click="handleSubmit" :disabled="!countryCode || isValidating">
      {{ isValidating ? 'Validating...' : submitLabel }}
    </button>

    <div v-if="errors.length > 0" class="validation-errors">
      <ul>
        <li v-for="(error, index) in errors" :key="index">{{ error }}</li>
      </ul>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useAddressValidation } from '../composables/useAddressValidation';

const props = defineProps<{
  countryCode?: string;
  submitLabel?: string;
}>();

const emit = defineEmits<{
  submit: [{ address: any; validation: any }];
}>();

const { validate, isValidating, errors } = useAddressValidation();

const countryCode = ref(props.countryCode || '');
const address = ref({
  street: '',
  city: '',
  postalCode: ''
});

const countries = [
  { code: 'JP', name: 'Japan' },
  { code: 'US', name: 'United States' },
  { code: 'GB', name: 'United Kingdom' }
];

async function handleSubmit() {
  const validation = await validate(address.value, countryCode.value);
  
  if (validation.valid) {
    emit('submit', { address: address.value, validation });
  }
}
</script>

<style scoped>
.vey-address-form {
  max-width: 500px;
}

.form-group {
  margin-bottom: 1rem;
}

label {
  display: block;
  margin-bottom: 0.25rem;
  font-weight: 500;
}

input, select {
  width: 100%;
  padding: 0.5rem;
  border: 1px solid #ccc;
  border-radius: 4px;
}

button {
  padding: 0.5rem 1rem;
  background-color: #00dc82;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

button:disabled {
  background-color: #ccc;
  cursor: not-allowed;
}

.validation-errors {
  margin-top: 1rem;
  padding: 0.5rem;
  background-color: #fee;
  border: 1px solid #fcc;
  border-radius: 4px;
  color: #c00;
}
</style>

// sdk/react-native/src/AddressForm.tsx
import React, { useState } from 'react';
import {
  View,
  Text,
  TextInput,
  Button,
  StyleSheet,
  ActivityIndicator,
} from 'react-native';
import { useAddressValidation } from './useAddressValidation';

interface AddressFormProps {
  countryCode: string;
  onSubmit?: (address: any, validation: any) => void;
  submitLabel?: string;
}

export function AddressForm({
  countryCode,
  onSubmit,
  submitLabel = 'Submit',
}: AddressFormProps) {
  const [address, setAddress] = useState({
    street: '',
    city: '',
    province: '',
    postalCode: '',
  });

  const { validate, isValidating, errors } = useAddressValidation();

  async function handleSubmit() {
    const validation = await validate(address, countryCode);
    
    if (validation.valid && onSubmit) {
      onSubmit(address, validation);
    }
  }

  return (
    <View style={styles.container}>
      <View style={styles.formGroup}>
        <Text style={styles.label}>Street Address</Text>
        <TextInput
          style={styles.input}
          value={address.street}
          onChangeText={(text) => setAddress({ ...address, street: text })}
          placeholder="Enter street address"
        />
      </View>

      <View style={styles.formGroup}>
        <Text style={styles.label}>City</Text>
        <TextInput
          style={styles.input}
          value={address.city}
          onChangeText={(text) => setAddress({ ...address, city: text })}
          placeholder="Enter city"
        />
      </View>

      <View style={styles.formGroup}>
        <Text style={styles.label}>Province/State</Text>
        <TextInput
          style={styles.input}
          value={address.province}
          onChangeText={(text) => setAddress({ ...address, province: text })}
          placeholder="Enter province/state"
        />
      </View>

      <View style={styles.formGroup}>
        <Text style={styles.label}>Postal Code</Text>
        <TextInput
          style={styles.input}
          value={address.postalCode}
          onChangeText={(text) => setAddress({ ...address, postalCode: text })}
          placeholder="Enter postal code"
        />
      </View>

      {isValidating ? (
        <ActivityIndicator size="large" color="#007bff" />
      ) : (
        <Button title={submitLabel} onPress={handleSubmit} />
      )}

      {errors.length > 0 && (
        <View style={styles.errorContainer}>
          {errors.map((error, index) => (
            <Text key={index} style={styles.errorText}>
              {error}
            </Text>
          ))}
        </View>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: 16,
  },
  formGroup: {
    marginBottom: 16,
  },
  label: {
    fontSize: 16,
    fontWeight: '500',
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 4,
    padding: 12,
    fontSize: 16,
  },
  errorContainer: {
    marginTop: 16,
    padding: 12,
    backgroundColor: '#fee',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#fcc',
  },
  errorText: {
    color: '#c00',
  },
});
